import Script from 'next/script';

export default function Head() {
	return (
		<>
			<title>DriveSmart</title>
			<meta
				content="width=device-width, initial-scale=1"
				name="viewport"
			/>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<Script
				src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-5YQZ5iZrXQqQ4q7Z3Y5Z4Z3Z2Z2Z2Z2&libraries=places"
				strategy="worker"
			/>
		</>
	);
}
